"""WebhookDelivery.last_attempt_at

Revision ID: dd73438750bc
Revises: e1f09e486473
Create Date: 2026-08-20 16:02:22.280901

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dd73438750bc"
down_revision: Union[str, Sequence[str], None] = "e1f09e486473"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "webhook_deliveries", sa.Column("last_attempt_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("webhook_deliveries", "last_attempt_at")
    # ### end Alembic commands ###
