from typing import Generic, TypeVar

from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.sql import Select

T = TypeVar("T")


class BaseRepository(Generic[T]):
    """
    Базовый репозиторий.

    Важно: репозиторий НЕ управляет транзакцией (не вызывает commit/rollback).
    Он только flush()-ит изменения в текущей транзакции, чтобы:
    - autogenerated поля (id, server_default) стали доступны через refresh();
    - вызывающий код (сервис) мог объединить несколько операций репозитория
      в одну атомарную транзакцию.
    commit()/rollback() — обязанность get_db() (см. core/database.py).
    """

    def __init__(self, session: AsyncSession, model: type[T]):
        self.session = session
        self.model = model

    async def create(self, **kwargs) -> T:
        """Создать запись (flush, но без commit)."""
        new_instance = self.model(**kwargs)
        self.session.add(new_instance)

        await self.session.flush()
        await self.session.refresh(new_instance)

        return new_instance

    async def update(self, id: int, **kwargs) -> T | None:
        """Обновить запись (flush, но без commit)."""
        instance = await self.get_by_id(id)
        if instance is None:
            return None

        for key, value in kwargs.items():
            if hasattr(instance, key):
                setattr(instance, key, value)

        await self.session.flush()
        await self.session.refresh(instance)

        return instance

    async def delete(self, id: int) -> bool:
        """Удалить запись (flush, но без commit)."""
        instance = await self.get_by_id(id)
        if instance is None:
            return False

        await self.session.delete(instance)
        await self.session.flush()

        return True

    async def get_by_id(self, id: int) -> T | None:
        """Получить по ID."""
        return await self.session.get(self.model, id)

    async def get_all(
        self,
        limit: int = 100,
        offset: int = 0,
    ) -> list[T]:
        """Получить все записи с пагинацией."""
        query = select(self.model).offset(offset).limit(limit)
        result = await self.session.execute(query)
        return list(result.scalars().all())

    async def count(self, query: Select | None = None) -> int:
        """
        Посчитать количество записей.

        Если передан query (например, из list_filtered наследника с уже
        применёнными .where()), считает по нему; иначе считает всю таблицу.
        """
        base = query if query is not None else select(self.model)
        count_query = select(func.count()).select_from(base.subquery())
        result = await self.session.execute(count_query)
        return result.scalar_one()
